services:
  app:
    image: ghcr.io/rayaadhary/landing-page-svelte:latest
    container_name: aorta-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    networks:
      - global-proxy

volumes:
  uploads:

networks:
  global-proxy:
    external: true
