services:
  app:
    build: .
    image: ghcr.io/rayaadhary/landing-page-svelte:latest
    container_name: aorta-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:rahasianantigwedit@pgbouncer:6432/aorta_cms
    depends_on:
      - pgbouncer
    networks:
      - global-proxy

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:rahasianantigwedit@postgres-pusat:5432/aorta_cms
      - POOL_MODE=transaction
      - DEFAULT_POOL_SIZE=20
      - MAX_CLIENT_CONN=200
      - AUTH_TYPE=plain
    networks:
      - global-proxy


networks:
  global-proxy:
    external: true
